"""payment table

Revision ID: 1c1625f49023
Revises: 5f2bf3830ad2
Create Date: 2024-05-20 14:24:09.917436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1625f49023'
down_revision = '5f2bf3830ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_payment_id'), ['payment_id'], unique=False)
        batch_op.create_foreign_key('fk_expense_payment', 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_payment_id'))
        batch_op.drop_column('payment_id')

    op.drop_table('payment')
    # ### end Alembic commands ###
