"""income

Revision ID: 5f2bf3830ad2
Revises: 8af159cc19fd
Create Date: 2024-05-10 13:28:59.894697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2bf3830ad2'
down_revision = '8af159cc19fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
