"""empty message

Revision ID: 65617b007c72
Revises: b38d402cf1ff
Create Date: 2024-05-20 15:44:08.446503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65617b007c72'
down_revision = 'b38d402cf1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expense_payment', 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
