"""empty message

Revision ID: 9341ad27243d
Revises: 12fdf5274f82
Create Date: 2024-05-02 22:07:27.559983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9341ad27243d'
down_revision = '12fdf5274f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_firstname')
        batch_op.drop_index('ix_user_lastname')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_lastname', ['lastname'], unique=False)
        batch_op.create_index('ix_user_firstname', ['firstname'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    # ### end Alembic commands ###
