"""empty message

Revision ID: 973e1e71c1c2
Revises: 1c1625f49023
Create Date: 2024-05-20 14:46:34.663567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973e1e71c1c2'
down_revision = '1c1625f49023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_payment_id'), ['payment_id'], unique=False)
        batch_op.create_foreign_key('fk_expense_payment', 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_payment_id'))
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
