"""empty message

Revision ID: ee68619094f8
Revises: f42282340ace
Create Date: 2024-05-20 15:18:02.413205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee68619094f8'
down_revision = 'f42282340ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_payment_id'), ['payment_id'], unique=False)
        batch_op.create_foreign_key('fk_expense_payment', 'payment', ['payment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_payment_id'))
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
